### ISSUE TITLE
Individual Contribution Krishiv Mahendru

### ISSUE THREAD

**Issue by Krishiv111** [divorced-coders/NewBooksBackend#3]
Krishiv Mahendru Individual Contributions 
-----------------------------------------

1. [Video and Demo of Key Contributions ](https://youtu.be/OLOkuEcbtes)

2. Issues and Planning/ 3.Highlight of Key Commits

- [ ] [Issue 1(Sorting Methods In Backend Progress)](https://github.com/divorced-coders/NewBooksBackend/issues/4)
- [ ] [Issue 2(Frontend Progress)](https://github.com/divorced-coders/NewBooksBackend/issues/5)

- [ ] [Issue 3(Individual Errors)](https://github.com/divorced-coders/NewBooksBackend/issues/6)
4. Github Analytics Issue 
- [ ] [Backend Commits ](https://github.com/divorced-coders/NewBooksBackend/commits/master)
- [ ] [Frontend Commits](https://github.com/divorced-coders/divorced_books_frontend/commits/main)

**Comment by paravsalaniwal** [comment]
Individual Review Parav Salaniwal grading Krishiv Mahendru

- [x] Individual should show that they were key contributor and example to team.  This includes their participation in ideas, plans, creating individual issues, providing code commits to project, crossover grading participation, being on task and positive example in the classroom.

Individuals Video, Issue(s), Commits(s)

- [x] Video, includes Web demo of key contribution to project, 1 minute
- [x] Issue(s) that show plans/progress to team objectives
- [x] Highlights of key commit(s) in Issues, summarizes code contributions
- [x] Review GitHub analytics for key commits in each weeks during the project, shows consistent participation for 3 weeks

 Per check.  
 0.55 not attempted/no check 
 0.7 attempted, incoomplete, but some runtime
 0.8 mastery and runtime 
 0.9 above and beyond.

> Grade given: 0.84/0.9

## Freeform

Using the coin API and parsing the data via JSON Parser to only output the transaction size in the backend file. Then used extends methods to sort transaction sizes via Heap sort and Bubble Sort. Used comparisons to get time taken for sorting and used various amounts of controlling methods. Worked on visualization feature on the frontend to show how sorting was done and time taken. 

### Tips

- Work on the UI of making this more visually appealing as well as adding more to the frontend display involving more about the Digital Currency

## Overall

Overall, Krishiv made a large contribution to his group and implemented key lessons such as the various sorting algorithms and parent-child classes to keep organized.
